### ISSUE TITLE
Invalid proof?

### ISSUE THREAD

**Issue by psygnisfive** [quchen/articles#52]
I think the following proof is invalid:

>    fmap f . fmap g
> = fmap id . fmap (f . g)
> = id . fmap (f . g)      -- by the first functor law
> = fmap (f . g)

The proof comes after a statement of an implication, and the  first equation in the proof is the antecedent of the implication. but this proof isn't used implicationally. It should read something more like

`if fmap f . fmap g = fmap id . fmap (f . g) then ...`

but that obviously doesn't help prove the second law.

**Comment by quchen** [comment]
Hey there, thanks for the question, it’s nice to see people still read my things thoroughly :-) I think the proof is right, but I do agree that the presentation could be a bit more precise. I’ll try to do better below. If it’s still wrong please do nag me about it!

# Proof

We start out with the free theorem for `fmap`,

```
∀ f g p q.
    f ∘ g = p ∘ q
    =>
    fmap f ∘ fmap g = fmap p ∘ fmap q
```

Since this works universally for all `p` and `q`, we are free to choose `p = id` and `q = f ∘ g`,

```
∀ f g.
    f ∘ g = id ∘ (f ∘ g)
    =>
    fmap f ∘ fmap g = fmap id ∘ fmap (f ∘ g)
```

Since the part before the `=>` is always true, the implication reduces to its consequence, giving us

```
∀ f g.
    fmap f ∘ fmap g = fmap id ∘ fmap (f ∘ g)
```

as claimed.

**Comment by psygnisfive** [comment]
You know, re-reading what you originally wrote, I'm not sure why I opened this issue in the first place. I must have been tired. Sorry :(

**Comment by quchen** [comment]
A good article would have been readable by a tired person as well! If you’ve got a suggestion for better presentation let me know :-)
